# Cloud Build configuration for automatic deployment to Cloud Run
# Repository: hack-for-social-impact-2025/justice-ai
# This file is triggered when you push to GitHub (after setting up Cloud Build trigger)
#
# COST-SAVING CONFIGURATION:
# - Only trigger on 'main' branch (configure in Cloud Build trigger settings)
# - Uses default E2 machine type (free tier: 120 build-minutes/day)
# - Estimated cost: $0.00/month for typical usage (1-3 builds/day)
# - Previous config (N1_HIGHCPU_8): ~$0.20-0.60/day for same usage

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backend-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backend-api:latest'
      - '.'
    dir: 'backend'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/backend-api:$COMMIT_SHA'

  # Step 3: Push the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/backend-api:latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend-api'
      - '--image=gcr.io/$PROJECT_ID/backend-api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=60s'
      - '--set-env-vars=DEBUG=False'
      - '--set-env-vars=^@^ALLOWED_ORIGINS=${_ALLOWED_ORIGINS}'
      - '--set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest'

# ==============================================================================
# 🔧 PRODUCTION CONFIGURATION
# ==============================================================================
# Update _ALLOWED_ORIGINS when deploying a new frontend URL:
#   1. Update the URL below (remove trailing slash!)
#   2. Commit and push to main branch
#   3. Cloud Build will automatically deploy with new CORS settings
#
# ⚠️ Important: Browser Origin headers don't include trailing slashes.
#    Use: https://your-app.vercel.app  ✅
#    NOT: https://your-app.vercel.app/ ❌
# ==============================================================================
substitutions:
  _ALLOWED_ORIGINS: 'https://justice-ai-h4si.vercel.app,https://hack-for-social-impact-two.vercel.app'

# Specify which resources to build
options:
  # Cost optimization: Use default E2 machine instead of N1_HIGHCPU_8
  # N1_HIGHCPU_8 costs ~8x more in build-minutes (8 cores = 8 build-minutes per actual minute)
  # Default E2 machine: ~1 build-minute per actual minute, stays within free tier (120 build-min/day)
  # machineType: 'N1_HIGHCPU_8'  # COMMENTED OUT: Expensive, only use for large builds

  # Cloud logging only (no legacy logging for cost efficiency)
  logging: CLOUD_LOGGING_ONLY

# Timeout for entire build (default is 10 minutes)
timeout: '600s'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/backend-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/backend-api:latest'
